# Decision Tree Implementation

In [1]:
import pandas as pd  
import numpy as np

In [2]:
df = pd.read_csv('Desktop/weather.csv')  
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,68,29,1019.7,1015.0,7,7,14.4,23.6,No,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,No

## Data Pre-processing

In [3]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 

df = df.dropna(axis = 0, how ='any') 


df['WindGustDir']= label_encoder.fit_transform(df['WindGustDir'].astype(str))

df['WindDir9am']= label_encoder.fit_transform(df['WindDir9am'].astype(str))

df['WindDir3pm']= label_encoder.fit_transform(df['WindDir3pm'].astype(str))

df['RainToday']= label_encoder.fit_transform(df['RainToday'].astype(str))

df['RainTomorrow']= label_encoder.fit_transform(df['RainTomorrow'].astype(str))

df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,7,30.0,12,7,6.0,...,68,29,1019.7,1015.0,7,7,14.4,23.6,0,1
1,14.0,26.9,3.6,4.4,9.7,1,39.0,0,13,4.0,...,80,36,1012.4,1008.4,5,3,17.5,25.7,1,1
2,13.7,23.4,3.6,5.8,3.3,7,85.0,3,5,6.0,...,82,69,1009.5,1007.2,8,7,15.4,20.2,1,1
3,13.3,15.5,39.8,7.2,9.1,7,54.0,14,13,30.0,...,62,56,1005.5,1007.0,2,7,13.5,14.1,1,1
4,7.6,16.1,2.8,5.6,10.6,10,50.0,10,2,20.0,...,68,49,1018.3,1018.5,7,7,11.1,15.4,1,0

## Feature Selection

In [4]:
X = df.iloc[:, 0:20].values  
y = df.iloc[:, 20].values

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

## Training the model

In [6]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [7]:
y_pred = classifier.predict(X_test)

## Evaluating the model

In [8]:
from sklearn.metrics import classification_report,  accuracy_score
  
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.83      0.87        66
           1       0.48      0.62      0.54        16

   micro avg       0.79      0.79      0.79        82
   macro avg       0.69      0.73      0.70        82
weighted avg       0.82      0.79      0.80        82

0.7926829268292683

## Demo Prediction

In [9]:
demo=[[10,29.5,1,4,4.1,6,48,5,6,19,17,70,48,1026.1,1022.7,7,8,14.1,18.9,0],[8,29.5,1,5,4.1,6,58,5,7,19,17,70,48,1026.1,1022.7,8,8,14.1,18.9,1]]
y=classifier.predict(demo)
int(round(y[1],0))

0